In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
raw_df = pd.read_csv(r"C:\Users\Amit Tiwari\OneDrive\Desktop\python\kaggle\Titanic-Dataset.csv")
raw_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
raw_df = pd.read_csv(r"C:\Users\Amit Tiwari\OneDrive\Desktop\python\kaggle\Titanic-Dataset.csv")
raw_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
new_df = raw_df[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch"]]
new_df.Age = new_df.Age.fillna(new_df.Age.mean()).round()
new_df.head()
sex_dict = { 
    "female" : 0,
    "male" : 1
}
new_df["Sex"] = new_df["Sex"].map(sex_dict)
result_series = raw_df["Survived"]

In [4]:
train_data,test_data,train_result,test_result = train_test_split(new_df,result_series,test_size=0.2,random_state=42)
model = LogisticRegression()
model.fit(train_data,train_result)
prediction = model.predict(test_data)
acc_score = accuracy_score(test_result,prediction)
print(f"Accracy Score : {acc_score:.2f}")

Accracy Score : 0.82

In [5]:
new_passenger = [[1, 1, 25, 100, 0, 0]]
will_survive = model.predict(new_passenger)
prob = model.predict_proba(new_passenger)
print(f"Probability of Survival : {prob.round(2)}")
print(f"If new passenger Survive? : {will_survive[0]}")

Probability of Survival : [[0.43 0.57]]
If new passenger Survive? : 1

C:\Users\Amit Tiwari\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\Amit Tiwari\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [10]:
coeff = model.coef_[0].tolist()
print(type(test_data.columns.tolist()))
print(test_data.columns.tolist())
dict_coeff = {
    "Features" : test_data.columns,
    "Coefficient" : model.coef_[0].tolist()
}
print(dict_coeff)
df_coeff = pd.DataFrame(dict_coeff)
print(df_coeff)

<class 'list'>
['Pclass', 'Sex', 'Age', 'Fare', 'SibSp', 'Parch']
{'Features': Index(['Pclass', 'Sex', 'Age', 'Fare', 'SibSp', 'Parch'], dtype='str'), 'Coefficient': [-0.9275579840775533, -2.6115509654144686, -0.03204351020846776, 0.0034199608259401055, -0.3176937414025402, -0.13004752644913736]}
  Features  Coefficient
0   Pclass    -0.927558
1      Sex    -2.611551
2      Age    -0.032044
3     Fare     0.003420
4    SibSp    -0.317694
5    Parch    -0.130048

In [12]:
cm = confusion_matrix(test_result,prediction)
cm

array([[92, 13],
       [20, 54]])